### ISSUE TITLE
[smartreact] error handling when emoji no longer exists

### ISSUE THREAD

**Issue by flapjax** [flapjax/FlapJack-Cogs#53]
```
Traceback (most recent call last):
  File "C:\Users\###\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\###\smartreact.py", line 110, in msg_listener
    await self.bot.add_reaction(message, self.fix_custom_emoji(emoji))
  File "C:\###\smartreact.py", line 51, in fix_custom_emoji
    return [r for server in self.bot.servers for r in server.emojis if r.id == emoji.split(':')[2][:-1]][0]
IndexError: list index out of range
Ignoring exception in message
```

the cog needs some error handling when an emoji stored in a smart reaction is being searched for and:
- it no longer exists
- the bot no longer has access to the emoji (due to loss of nitro or leaving the server)

(reported by UIGb7#4007)

**Comment by flapjax** [comment]
Fixed.
