### ISSUE TITLE
bigmoji cog was unable to load

### ISSUE THREAD

**Issue by endms3231** [flapjax/FlapJack-Cogs#75]
bigmoji cog was unable to load from redbot, could i get some help?
i had write down how the problem happens.

first: [p]repo add FlapJack-Cogs https://github.com/flapjax/FlapJack-Cogs red-v3-rewrites
- ok!
second: [p]cog install FlapJack-Cogs bigmoji
- ok!
third: [p]load bigmoji
- Failed to load package bigmoji. Check your console or logs for details.

Using CairoSVG for svg conversion.
[06/09/2018 02:12] ERROR core_commands _load 97: Package loading failed
Traceback (most recent call last):
  File "/home/amadeus/.local/lib/python3.6/site-packages/redbot/core/core_commands.py", line 95, in _load
    await bot.load_extension(spec)
  File "/home/amadeus/.local/lib/python3.6/site-packages/redbot/core/bot.py", line 228, in load_extension
    lib.setup(self)
  File "/home/amadeus/.local/share/Red-DiscordBot/cogs/CogManager/cogs/bigmoji/__init__.py", line 5, in setup
    bot.add_cog(Bigmoji(bot))
  File "/home/amadeus/.local/lib/python3.6/site-packages/redbot/core/bot.py", line 334, in add_cog
    f"The {cog.__class__.__name__} cog in the {cog.__module__} package,"
RuntimeError: The Bigmoji cog in the bigmoji.bigmoji package, is not using Red's command module, and cannot be added. If this is your cog, please use `from redbot.core import commands`in place of `from discord.ext import commands`. For more details on this requirement, see this page: http://red-discordbot.readthedocs.io/en/v3-develop/framework_commands.html

**Comment by flapjax** [comment]
Thanks for the report, this has been fixed on the red-v3-rewrites branch.

**Comment by endms3231** [comment]
Thanks watching :P

Windows 10용 메일에서 보냄

보낸 사람: flapjax
보낸 날짜: 2018년 11월 27일 화요일 오전 6:40
받는 사람: flapjax/FlapJack-Cogs
참조: 이리에; Author
제목: Re: [flapjax/FlapJack-Cogs] bigmoji cog was unable to load (#75)

Thanks for the report, this has been fixed on the red-v3-rewrites branch.
