### ISSUE TITLE
[SFX] Error on addsfx

### ISSUE THREAD

**Issue by Schtroumpf9** [flapjax/FlapJack-Cogs#82]
So this is the console log I get when I try to use the command:
[07/11/2018 00:31] ERROR red on_command_error 369: Exception in command 'addsfx'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "D:\Programs\Red-DiscordBot\cogs\sfx.py", line 385, in addsfx
    async with self.session.get(url) as new_sound:
  File "lib\aiohttp\client.py", line 565, in __aenter__
    self._resp = yield from self._coro
  File "lib\aiohttp\client.py", line 195, in _request
    proxy=proxy, proxy_auth=proxy_auth, timeout=timeout)
  File "lib\aiohttp\client_reqrep.py", line 91, in __init__
    self.update_host(url)
  File "lib\aiohttp\client_reqrep.py", line 111, in update_host
    raise ValueError('Host could not be detected.')
ValueError: Host could not be detected.

**Comment by flapjax** [comment]
It appears you're having trouble adding a sound file via url, because the system your bot is running on can't resolve the host. This could be due to a number of issues. If the url is reachable from your own computer, the quickest solution would be to download the file yourself and add it by uploading it as a Discord attachment with the comment being your 'addsfx' command.

**Comment by Schtroumpf9** [comment]
Oh, interesting, that worked. I had no idea the sound had to be uploaded somewhere. I was just trying to add/play it locally.
