### ISSUE TITLE
[msgvote] V3 not working?

### ISSUE THREAD

**Issue by JTTM** [flapjax/FlapJack-Cogs#93]
`Exception during loading of cog
Traceback (most recent call last):
  File "/home/jonttm/red/lib/python3.6/site-packages/redbot/core/core_commands.py", line 104, in _load
    await bot.load_extension(spec)
  File "/home/jonttm/red/lib/python3.6/site-packages/redbot/core/bot.py", line 233, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jonttm/red/share/Red-DiscordBot/cogs/CogManager/cogs/msgvote/__init__.py", line 1, in <module>
    from .msgvote import MsgVote
  File "/home/jonttm/red/share/Red-DiscordBot/cogs/CogManager/cogs/msgvote/msgvote.py", line 12, in <module>
    class MsgVote(BaseCog):
  File "/home/jonttm/red/share/Red-DiscordBot/cogs/CogManager/cogs/msgvote/msgvote.py", line 44, in MsgVote
    @checks.admin_or_permissions(manage_server=True)
  File "/home/jonttm/red/lib/python3.6/site-packages/discord/ext/commands/core.py", line 1179, in decorator
    return cls(name=fname, callback=func, checks=checks, cooldown=cooldown, **attrs)
  File "/home/jonttm/red/lib/python3.6/site-packages/redbot/core/commands/commands.py", line 430, in __init__
    super().__init__(*args, **kwargs)
  File "/home/jonttm/red/lib/python3.6/site-packages/redbot/core/commands/commands.py", line 118, in __init__
    super().__init__(*args, **kwargs)
  File "/home/jonttm/red/lib/python3.6/site-packages/redbot/core/commands/commands.py", line 50, in __init__
    checks=getattr(decorated, "__requires_checks__", []),
  File "/home/jonttm/red/lib/python3.6/site-packages/redbot/core/commands/requires.py", line 299, in __init__
    _validate_perms_dict(user_perms)
  File "/home/jonttm/red/lib/python3.6/site-packages/redbot/core/commands/requires.py", line 718, in _validate_perms_dict
    raise TypeError(f"Unknown permission name '{perm}'")
TypeError: Unknown permission name 'manage_server'`

Any ideas?

**Comment by aikaterna** [comment]
See PR #89 for the resolution, not merged yet
