### ISSUE TITLE
[reactpoll] in Red-v3-rewrites errors when timer ends

### ISSUE THREAD

**Issue by designbyadrian** [flapjax/FlapJack-Cogs#94]
`[p]rpoll "Are you happy that polls are back?" "Hell yeah! Thank you so much!;No, I'm fucking miserable and should kys myself" "240s"`

> 240 seconds pass...

`Error in command 'rpoll'. Check your console or logs for details.`

Error log:

```
Traceback (most recent call last):
  File "/home/designbyadrian/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/reactpoll/reactpoll.py", line 222, in rpoll
    poll = NewPoll(ctx, self, question, options, duration)
  File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/reactpoll/reactpoll.py", line 27, in __init__
    self.end_time = self.parse_duration(duration)
  File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/reactpoll/reactpoll.py", line 58, in parse_duration
    value = int(text[:idx])
  ValueError: invalid literal for int() with base 10: ''
```

_Edit: poll eventually ends successfully with results anyway! Error appears roughly 60s later, and the results 180s after that (that is, after 240s as per command)._

**Comment by Ruined1** [comment]
Used the exact command as you listed:
`[p]rpoll "Are you happy that polls are back?" "Hell yeah! Thank you so much!;No, I'm fucking miserable and should kys myself" "240s"`

Wasn't reproducible.

**Comment by aikaterna** [comment]
Hi, I was only able to get this error when I passed `""` for the time, and was unable to repro this as you presented it. However, I made it so that if a blank string is passed like that it will return None as expected. Hopefully 2eaafdb fixes this for you, and if not, please leave another comment with your traceback.
