### ISSUE TITLE
[smartreact] error while addreact

### ISSUE THREAD

**Issue by Weirdo914** [flapjax/FlapJack-Cogs#97]
When running addreact the following error appears-

Additional Info-
RedBot- v2
Python- v3.5.2

```Creating data/smartreact folder...
Creating default smartreact settings.json...
[24/05/2019 15:19] ERROR red on_command_error 388: Exception in command 'addreact'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pokemonfanscool/Red-DiscordBot/cogs/smartreact.py", line 25, in addreact
    trigger, emoji = parse_command(command)
  File "/home/pokemonfanscool/Red-DiscordBot/cogs/smartreact.py", line 149, in parse_command
    emoji = command[-1]
IndexError: tuple index out of range

**Comment by aikaterna** [comment]
Hi, this is resolved in c1781c3.
